### ISSUE TITLE
Github Data Collector

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-data#1]
## Overview

As a web3studio team member, I want an aggregated view of my GitHub interaction data so I can better serve the community and follow trends easier.

### Assumptions

- Github stats will be sent to ELK
- Serverless lambdas on a timer will collect data
    - Webhooks take more work to keep active, prefer polling

### Acceptance

- Github statistics across all web3studio projects will be sent to Elk
- Dimensions will be sent to indicate if an action was taken by a Web3studio team member, a ConsenSys employee, or outside ConsenSys.
- Data should include as much data for tracing and potential cohort analysis as possible, repo, users, etc
- Data collected on a regular bases 
- The whole team can access data from the web

## Tasks

- [x] Create monorepo
- [x] Setup Travis linting etc
- [x] Collect stargazers
- [x] Collect fork-ers
- [x] Tests!
- [x] Function run's difs from last time
- [x] Create and authorize our team to AWS-ES
- [ ] Write and deploy lambda

**Comment by barlock** [comment]
Test comment!
